### ISSUE TITLE
Failed to to lint code that uses the `paste` macro

### ISSUE THREAD

**Issue by nsarlin-zama** [GuillaumeGomez/rustc-tools#30]
First, thank you for this really useful package !

It seems that calling a tool on a crate that uses the [paste](https://docs.rs/paste/latest/paste/) macro fails because of a failed import:
```
   |
8  |           paste::paste! {
   |           ^^^^^ use of undeclared crate or module `paste`
```
However, the same code can be built with `cargo build` or linted `cargo clippy`. I have created a minimum reproducing example here: https://github.com/nsarlin-zama/test_lint_paste. Using the [example tool](https://github.com/GuillaumeGomez/rustc-tools-example) on this crate returns the aforementioned error.

Thanks for your help

**Comment by GuillaumeGomez** [comment]
All done. I was not allowing `proc-macro`, so in this case it was not passed as dependency. I'm releasing `0.78.1` so you will be able to resume having fun with it. ;)

Thanks for the detailed issue!

**Comment by nsarlin-zama** [comment]
It works, thanks !
